name: Build AHK to EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install AutoHotkey v1
        run: |
          choco install autohotkey.portable -y

      - name: Compile AHK to EXE
        run: |
          "C:\ProgramData\chocolatey\lib\autohotkey.portable\tools\AutoHotkey\Compiler\Ahk2Exe.exe" /in spoof.ahk /out loader.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: loader-exe
          path: loader.exe
